### ISSUE TITLE
Set Plesk Port

### ISSUE THREAD

**Issue by canerd7u** [nickurt/laravel-plesk-xml#3]
My plesk panel using **8444** port. 

How to set package api port ?

**Comment by nickurt** [comment]
hi @canerd7u,

Just tagged 0.5.1 with the possibility to set a custom port (via `port`-option (default 8443)) via configuration-file

```php
'custom' => [
    'host' => 'xml-plesk-xml.tld',
    'port' => 8444,
    'username' => 'xml-plesk-xml',
    'password' => 'plesk-xml-plesk',
]
```
