### ISSUE TITLE
Using API Key

### ISSUE THREAD

**Issue by huabor** [nickurt/laravel-plesk-xml#4]
Is it possible to implement the authentification with plesk API Keys instead of Username and Password?

**Comment by nickurt** [comment]
Hi huabor,

I can update/add this behaviour this weekend.

**Comment by huabor** [comment]
Hey nickurt, are you able to implement the feature?

**Comment by nickurt** [comment]
Yes, I will try to do it in the coming days, sadly I didn't had time last weekend.

If possible, feel free to make a PR/suggestion.

**Comment by nickurt** [comment]
Hi huabor, 

I added support for secret/key based auth in the latest master-commit, you can use it when you add 
```php
'key' => env('PLESK_DEFAULT_KEY'),
```
to your existing config-file
